import type { Phase, Milestone } from '../types';
import { PHASE_COLORS } from './colors';

// Default ID timeline milestones (phase-agnostic, positioned on full project timeline)
export const DEFAULT_MILESTONES: Omit<Milestone, 'id' | 'sectionId'>[] = [
  {
    name: 'Design Freeze',
    description: 'Lock final design specifications',
    relativePosition: 0.6, // End of Design Development phase
    order: 0,
  },
  {
    name: 'Launch',
    description: 'Product launch milestone',
    relativePosition: 1, // End of project
    order: 1,
  },
];

// Default Industrial Design phases based on the standard product development process
export const DEFAULT_PHASES: Omit<Phase, 'id' | 'sectionId'>[] = [
  {
    name: 'Discovery & Research',
    description: 'Market research, user research, competitive analysis, requirements definition',
    color: PHASE_COLORS.discovery,
    order: 0,
    isCollapsed: false,
    relativeStart: 0,
    relativeEnd: 0.15,
    elements: [
      {
        id: '',
        phaseId: '',
        name: 'Market Research',
        description: 'Analyze market trends and opportunities',
        relativeStart: 0,
        relativeEnd: 0.4,
        order: 0,
      },
      {
        id: '',
        phaseId: '',
        name: 'User Research',
        description: 'Conduct user interviews and surveys',
        relativeStart: 0.2,
        relativeEnd: 0.7,
        order: 1,
      },
      {
        id: '',
        phaseId: '',
        name: 'Competitive Analysis',
        description: 'Evaluate competitor products',
        relativeStart: 0.3,
        relativeEnd: 0.8,
        order: 2,
      },
      {
        id: '',
        phaseId: '',
        name: 'Requirements Definition',
        description: 'Define product requirements and constraints',
        relativeStart: 0.6,
        relativeEnd: 1,
        order: 3,
      },
    ],
  },
  {
    name: 'Concept Development',
    description: 'Ideation, sketching, concept refinement, concept selection, initial prototyping',
    color: PHASE_COLORS.concept,
    order: 1,
    isCollapsed: false,
    relativeStart: 0.15,
    relativeEnd: 0.35,
    elements: [
      {
        id: '',
        phaseId: '',
        name: 'Ideation & Sketching',
        description: 'Generate and sketch initial concepts',
        relativeStart: 0,
        relativeEnd: 0.4,
        order: 0,
      },
      {
        id: '',
        phaseId: '',
        name: 'Concept Refinement',
        description: 'Refine promising concepts',
        relativeStart: 0.3,
        relativeEnd: 0.7,
        order: 1,
      },
      {
        id: '',
        phaseId: '',
        name: 'Concept Selection',
        description: 'Select final concept direction',
        relativeStart: 0.5,
        relativeEnd: 0.8,
        order: 2,
      },
      {
        id: '',
        phaseId: '',
        name: 'Initial Prototyping',
        description: 'Create early prototypes for testing',
        relativeStart: 0.7,
        relativeEnd: 1,
        order: 3,
      },
    ],
  },
  {
    name: 'Design Development',
    description: 'Form development, CMF, ergonomics, design refinement',
    color: PHASE_COLORS.design,
    order: 2,
    isCollapsed: false,
    relativeStart: 0.35,
    relativeEnd: 0.6,
    elements: [
      {
        id: '',
        phaseId: '',
        name: 'Form Development',
        description: 'Develop detailed form and aesthetics',
        relativeStart: 0,
        relativeEnd: 0.4,
        order: 0,
      },
      {
        id: '',
        phaseId: '',
        name: 'CMF Development',
        description: 'Color, material, and finish selection',
        relativeStart: 0.2,
        relativeEnd: 0.6,
        order: 1,
      },
      {
        id: '',
        phaseId: '',
        name: 'Ergonomics',
        description: 'Human factors and ergonomic optimization',
        relativeStart: 0.3,
        relativeEnd: 0.7,
        order: 2,
      },
      {
        id: '',
        phaseId: '',
        name: 'Design Refinement',
        description: 'Final design adjustments and polish',
        relativeStart: 0.6,
        relativeEnd: 1,
        order: 3,
      },
    ],
  },
  {
    name: 'Engineering & Detailing',
    description: 'DFM, technical documentation, tooling development, engineering samples',
    color: PHASE_COLORS.engineering,
    order: 3,
    isCollapsed: false,
    relativeStart: 0.6,
    relativeEnd: 0.85,
    elements: [
      {
        id: '',
        phaseId: '',
        name: 'Design for Manufacturing',
        description: 'Optimize design for production',
        relativeStart: 0,
        relativeEnd: 0.4,
        order: 0,
      },
      {
        id: '',
        phaseId: '',
        name: 'Technical Documentation',
        description: 'Create detailed technical specifications',
        relativeStart: 0.2,
        relativeEnd: 0.6,
        order: 1,
      },
      {
        id: '',
        phaseId: '',
        name: 'Tooling Development',
        description: 'Develop manufacturing tooling',
        relativeStart: 0.4,
        relativeEnd: 0.8,
        order: 2,
      },
      {
        id: '',
        phaseId: '',
        name: 'Engineering Samples',
        description: 'Produce and validate engineering samples',
        relativeStart: 0.7,
        relativeEnd: 1,
        order: 3,
      },
    ],
  },
  {
    name: 'Production Preparation',
    description: 'Pilot production, quality validation, production ramp-up',
    color: PHASE_COLORS.production,
    order: 4,
    isCollapsed: false,
    relativeStart: 0.85,
    relativeEnd: 1,
    elements: [
      {
        id: '',
        phaseId: '',
        name: 'Pilot Production',
        description: 'Initial small-scale production run',
        relativeStart: 0,
        relativeEnd: 0.4,
        order: 0,
      },
      {
        id: '',
        phaseId: '',
        name: 'Quality Validation',
        description: 'Validate quality standards',
        relativeStart: 0.3,
        relativeEnd: 0.7,
        order: 1,
      },
      {
        id: '',
        phaseId: '',
        name: 'Production Ramp-up',
        description: 'Scale up to full production',
        relativeStart: 0.6,
        relativeEnd: 1,
        order: 2,
      },
    ],
  },
];
